# Generated by Django 4.1.1 on 2022-09-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, unique=True)),
                ('apellido', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefonos', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='usuar/media')),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulante',
                'ordering': ('nombres',),
            },
        ),
    ]
