# Generated by Django 4.1.1 on 2022-09-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Empresa')),
                ('contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('Logo', models.FileField(blank=True, null=True, upload_to='usuar/media', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
                'ordering': ('nombre',),
            },
        ),
        migrations.RenameField(
            model_name='postulante',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
