# Generated by Django 4.1.1 on 2022-09-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuar', '0002_empresa_rename_apellido_postulante_apellidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ('Nombre',), 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresa'},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='contacto',
            new_name='Contacto',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='correo',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
