# Generated by Django 4.1.1 on 2022-09-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuar', '0003_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ('nombre',), 'verbose_name': 'Empresa'},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='Contacto',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='Logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
