# Generated by Django 4.1.1 on 2022-09-24 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuar', '0004_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='logo',
        ),
    ]
