# Generated by Django 4.1.1 on 2022-09-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuar', '0005_remove_empresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='apellidos',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='nombres',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='telefonos',
            field=models.CharField(max_length=10),
        ),
    ]
