# Generated by Django 4.1.1 on 2022-09-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuar', '0007_empresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='usuar/media'),
        ),
    ]
