# Generated by Django 4.1.1 on 2022-09-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuar', '0009_alter_empresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='contacto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
