# Generated by Django 4.1.1 on 2022-09-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuar', '0010_alter_empresa_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='promo',
            field=models.FileField(blank=True, null=True, upload_to='logo/empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='promo1',
            field=models.FileField(blank=True, null=True, upload_to='logo/empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='promo2',
            field=models.FileField(blank=True, null=True, upload_to='logo/empresa'),
        ),
    ]
