# Generated by Django 4.1.1 on 2022-09-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuar', '0011_empresa_promo_empresa_promo1_empresa_promo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='contacto',
            field=models.CharField(max_length=10),
        ),
    ]
